image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - if [ -f env/base.txt ]; then pip install -r env/base.txt; fi
            - pip install pytest
            - pytest -v tests/* --junitxml=test-reports/report.xml
      - step:
        name: Deploy to production
        deployment: production
        script:
          - echo "Deploying to production environment"
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              SSH_USER: 'yimba'
              SERVER: '139.162.236.207'
              COMMAND: '/home/yimba/deploy.sh'
