version: '3.9'

services:

  web.yimba.io:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ["gunicorn", "--bind", ":5000", "--workers", "3", "-m", "007", "runserver:yimba_app"]
    volumes:
      - .:/web/app
    ports:
      - ${APP_PORT}:5000
    depends_on:
      - cache.redis.io
    env_file:
      - dotenv/dev.env

  cache.redis.io:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --loglevel ${REDIS_LOG_LEVEL} --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 3
    env_file:
      - dotenv/redis.env

volumes:
  redis_data: {}

networks:
  default:
    driver: bridge
