version: '3.9'

services:

  web.yimba.io:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 -m 007 runserver:yimba_app
    volumes:
      - .:/web/app
    ports:
      - ${APP_PORT}:5000
    env_file:
      - dotenv/dev.env
