version: '3.9'

services:

  web.yimba.io:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 -m 007 runserver:yimba_app
    volumes:
      - .:/web/app
    ports:
      - ${APP_PORT}:5000
    depends_on:
      - cache.redis.io
    env_file:
      - dotenv/dev.env

  cache.redis.io:
    image: redis:alpine
    restart: always
    command: redis-server --loglevel ${REDIS_LOG_LEVEL} --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    env_file:
      - dotenv/redis.env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 3

volumes:
  redis_data: {}
