version: '3.9'

services:
  
  db.yimba.io:
    image: postgres:13
    command: postgres -c 'max_connections=${PG_MAX_CONNECTIONS}'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data/
    healthcheck:
      test: "exit 0"

  web.yimba.io:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python runserver.py 0.0.0.0:5000
    volumes:
      - .:/yimba
    env_file:
      - ./.flaskenv
    ports:
      - 5000:5000
    depends_on:
      - db.yimba.io

volumes:
  db:
